from pptx import Presentation
from pptx.util import Inches, Pt
import os

# Step-by-step explanation content
steps = [
    ("Step 1: Threading in Python",
     "Python's threading is limited by the Global Interpreter Lock (GIL), which prevents true parallel execution of threads. Threads are useful for I/O-bound tasks, not CPU-bound ones."),

    ("Step 2: Multiprocessing in Python",
     "Multiprocessing in Python avoids the GIL by running tasks in separate processes, each with its own Python interpreter and memory space. This allows true parallelism at the cost of more memory and overhead."),

    ("Step 3: Python's GIL Explained",
     "The GIL ensures that only one thread executes Python bytecode at a time. This makes CPython simpler but limits CPU-bound multithreaded performance."),

    ("Step 4: Multiprocessing Overhead",
     "While multiprocessing allows parallelism, it has overhead due to data serialization, memory duplication, and inter-process communication."),

    ("Step 5: Go's Goroutines",
     "Go uses goroutines for concurrency. They are lightweight, managed by the Go runtime, and not subject to a GIL. Goroutines can execute in parallel using multiple OS threads."),

    ("Step 6: Summary - Python vs Go",
     "Python excels at rapid development and I/O-bound tasks with threads. Go is better suited for scalable, parallel, CPU-bound applications due to its built-in concurrency model.")
]

# Create presentation
prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
content_slide_layout = prs.slide_layouts[1]
blank_slide_layout = prs.slide_layouts[6]

# Title slide
slide = prs.slides.add_slide(title_slide_layout)
slide.shapes.title.text = "Concurrency in Python vs Go"
slide.placeholders[1].text = "Step-by-step explanation and code comparison"

# Add explanation slides
for title_text, body_text in steps:
    slide = prs.slides.add_slide(content_slide_layout)
    slide.shapes.title.text = title_text
    slide.placeholders[1].text = body_text

# Add code slides for step1.py–step4.py and step1.go–step5.go
code_files = [f"step{i}.py" for i in range(1, 5)] + [f"step{i}.go" for i in range(1, 6)]

for filename in code_files:
    slide = prs.slides.add_slide(blank_slide_layout)
    left_title = Inches(0.5)
    top_title = Inches(0.3)
    #slide.shapes.title = slide.shapes.add_textbox(left_title, top_title, Inches(9), Inches(0.5))
    
    title_box = slide.shapes.add_textbox(left_title, top_title, Inches(9), Inches(0.5))
    title_frame = title_box.text_frame
    title_frame.text = f"Code: {filename}"
    #title_frame = slide.shapes.title.text_frame
    title_frame.text = f"Code: {filename}"

    try:
        with open(filename, 'r') as f:
            lines = f.readlines()
        snippet_lines = lines[:50]
        split_index = len(snippet_lines) // 2
        col1 = ''.join(snippet_lines[:split_index])
        col2 = ''.join(snippet_lines[split_index:])

        left_box = slide.shapes.add_textbox(Inches(0.5), Inches(1), Inches(4.5), Inches(5))
        right_box = slide.shapes.add_textbox(Inches(5.0), Inches(1), Inches(4.5), Inches(5))

        left_frame = left_box.text_frame
        left_frame.word_wrap = True
        left_run = left_frame.paragraphs[0].add_run()
        left_run.text = col1
        left_run.font.size = Pt(10)

        right_frame = right_box.text_frame
        right_frame.word_wrap = True
        right_run = right_frame.paragraphs[0].add_run()
        right_run.text = col2
        right_run.font.size = Pt(10)

    except FileNotFoundError:
        error_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(8), Inches(2))
        frame = error_box.text_frame
        frame.text = f"The file {filename} does not exist."
        frame.paragraphs[0].runs[0].font.size = Pt(12)

# Save presentation
output_path = "Python_vs_Go_Concurrency_Slides_AutoGenerated.pptx"
prs.save(output_path)
print(f"✅ Presentation saved as: {output_path}")
